import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import agentsRouter from "./agents";
import agentRosterRouter from "./agentRoster";
import inboxRouter from "./inbox";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import calendarRouter from "./calendar";
import communicationsRouter from "./communications";
import automationsRouter from "./automations";
import securityRouter from "./security";
import vaultRouter from "./vault";
import researchRouter from "./research";
import memoryRouter from "./memory";
import approvalsRouter from "./approvals";
import insightsRouter from "./insights";
import modesRouter from "./modes";
import marketplaceRouter from "./marketplace";
import telemetryRouter from "./telemetry";
import feedRouter from "./feed";
import connectorsRouter from "./connectors";
import voiceRouter from "./voice";
import authRouter from "./auth";
import agentConversationsRouter from "./agent-conversations";
import commandRouter from "./command";
import taskRunsRouter from "./task-runs";
import schedulerRouter from "./scheduler";
import spotifyRouter from "./spotify";
import weatherRouter from "./weather";
import onboardingRouter from "./onboarding";
import outlookSkillsRouter from "./outlookSkills";
import outlookSummarizeRouter from "./outlookSummarize";
import outlookTriageRouter from "./outlookTriage";
import outlookMessagesRouter from "./outlookMessages";
import gmailSkillsRouter from "./gmailSkills";
import gmailMessagesRouter from "./gmailMessages";
import skillSetsRouter from "./skillSets";
import workDomainsRouter from "./workDomains";
import integrationsRouter from "./integrations";
import actionReceiptsRouter from "./actionReceipts";
import quotaRouter from "./quota";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/telemetry", telemetryRouter);
router.use("/feed", feedRouter);
router.use("/connectors", connectorsRouter);
router.use("/voice", voiceRouter);
router.use("/auth", authRouter);
router.use("/dashboard", dashboardRouter);
router.use("/agents", agentRosterRouter);
router.use("/agents", agentsRouter);
router.use("/inbox", inboxRouter);
router.use("/projects", projectsRouter);
router.use("/tasks", tasksRouter);
router.use("/calendar", calendarRouter);
router.use("/communications", communicationsRouter);
router.use("/automations", automationsRouter);
router.use("/security", securityRouter);
router.use("/vault", vaultRouter);
router.use("/research", researchRouter);
router.use("/memory", memoryRouter);
router.use("/approvals", approvalsRouter);
router.use("/insights", insightsRouter);
router.use("/modes", modesRouter);
router.use("/marketplace", marketplaceRouter);
router.use("/agent-conversations", agentConversationsRouter);
router.use("/command", commandRouter);
router.use("/task-runs", taskRunsRouter);
router.use("/scheduler", schedulerRouter);
router.use("/spotify", spotifyRouter);
router.use("/weather", weatherRouter);
router.use("/onboarding", onboardingRouter);
router.use("/skills/outlook-draft-email", outlookSkillsRouter);
router.use("/skills/outlook-summarize-thread", outlookSummarizeRouter);
router.use("/skills/outlook-triage-inbox", outlookTriageRouter);
router.use("/skills/outlook-messages", outlookMessagesRouter);
router.use("/skills/gmail-draft-email", gmailSkillsRouter);
router.use("/skills/gmail-messages", gmailMessagesRouter);
router.use("/skill-sets", skillSetsRouter);
router.use("/work-domains", workDomainsRouter);
router.use("/integrations", integrationsRouter);
router.use("/action-receipts", actionReceiptsRouter);
router.use("/quota", quotaRouter);

export default router;
