// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/overlay-redesign/OverlayRedesign.tsx": () => import("../components/mockups/overlay-redesign/OverlayRedesign.tsx"),
  "./components/mockups/nexus-canvas/NexusCanvas.tsx": () => import("../components/mockups/nexus-canvas/NexusCanvas.tsx")
};
