import { db } from "@workspace/db";
import { eq } from "drizzle-orm";
import {
  agentsTable,
  inboxItemsTable,
  projectsTable,
  tasksTable,
  calendarEventsTable,
  communicationsTable,
  automationsTable,
  securityEventsTable,
  securityLayersTable,
  researchItemsTable,
  memoryItemsTable,
  approvalsTable,
  insightsTable,
  operatingModesTable,
  marketplaceAgentsTable,
} from "@workspace/db";

async function seed() {
  console.log("Seeding Khameleon Command database...");

  // Operating Modes
  await db.insert(operatingModesTable).values([
    { name: "Work Mode", description: "Standard professional configuration", icon: "Briefcase", isActive: true, color: "#00d4ff" },
    { name: "Founder Mode", description: "High-level strategic focus with all alerts", icon: "Rocket", isActive: false, color: "#c9a84c" },
    { name: "Family Mode", description: "Personal priorities, limit work notifications", icon: "Heart", isActive: false, color: "#10b981" },
    { name: "Finance Mode", description: "Financial dashboards and market feeds", icon: "TrendingUp", isActive: false, color: "#8b5cf6" },
    { name: "Travel Mode", description: "Travel schedules, timezone adjustments", icon: "Globe", isActive: false, color: "#3b82f6" },
    { name: "Meeting Mode", description: "Focused on upcoming meetings and prep", icon: "Users", isActive: false, color: "#f59e0b" },
    { name: "Deep Focus", description: "All notifications muted, single task view", icon: "Target", isActive: false, color: "#ef4444" },
    { name: "Private Mode", description: "Sensitive data hidden, full privacy", icon: "Shield", isActive: false, color: "#6b7280" },
  ]);

  // AI Agents
  await db.insert(agentsTable).values([
    {
      name: "Email Agent",
      description: "Handles email composition, analysis, prioritisation, and automated responses across all connected mail services.",
      category: "Communication",
      reliabilityScore: 98,
      costScore: 95,
      status: "active",
      supportedModels: ["GPT-4o", "Claude 3.5 Sonnet", "Gemini Pro"],
      strengths: ["Email composition", "Sentiment analysis", "Thread summarisation", "Priority detection"],
      useCases: ["Draft replies", "Summarise inbox", "Flag urgent items", "Auto-respond"],
      permissions: ["read:email", "write:email", "send:email"],
      tasksCompleted: 1452,
      avgResponseTime: 0.8,
    },
    {
      name: "Calendar Agent",
      description: "Manages scheduling, meeting preparation, conflict resolution, and agenda creation across calendar systems.",
      category: "Productivity",
      reliabilityScore: 99,
      costScore: 97,
      status: "active",
      supportedModels: ["GPT-4o", "Claude 3.5 Sonnet"],
      strengths: ["Scheduling optimisation", "Meeting briefs", "Conflict detection", "Travel time estimation"],
      useCases: ["Schedule meetings", "Prepare briefings", "Resolve conflicts", "Block focus time"],
      permissions: ["read:calendar", "write:calendar"],
      tasksCompleted: 2034,
      avgResponseTime: 0.5,
    },
    {
      name: "Research Agent",
      description: "Conducts deep internet research, competitive analysis, and synthesises information into actionable reports.",
      category: "Intelligence",
      reliabilityScore: 94,
      costScore: 78,
      status: "active",
      supportedModels: ["GPT-4o", "Claude 3.5 Sonnet", "Perplexity"],
      strengths: ["Web search", "Source verification", "Report generation", "Competitive analysis"],
      useCases: ["Research competitors", "Summarise articles", "Fact-check information", "Market analysis"],
      permissions: ["read:web", "write:documents"],
      tasksCompleted: 876,
      avgResponseTime: 3.2,
    },
    {
      name: "Coding Agent",
      description: "Writes, reviews, debugs, and documents code across multiple languages and frameworks.",
      category: "Engineering",
      reliabilityScore: 96,
      costScore: 72,
      status: "active",
      supportedModels: ["GPT-4o", "Claude 3.5 Sonnet", "DeepSeek Coder"],
      strengths: ["Code generation", "Bug detection", "Code review", "Documentation"],
      useCases: ["Write code", "Debug issues", "Review PRs", "Generate tests"],
      permissions: ["read:repositories", "write:code", "read:issues"],
      tasksCompleted: 623,
      avgResponseTime: 4.1,
    },
    {
      name: "Design Agent",
      description: "Creates UI mockups, design specifications, and visual assets for digital products.",
      category: "Creative",
      reliabilityScore: 91,
      costScore: 68,
      status: "active",
      supportedModels: ["DALL-E 3", "Midjourney", "Stable Diffusion XL"],
      strengths: ["UI design", "Image generation", "Brand guidelines", "Prototype creation"],
      useCases: ["Create mockups", "Generate images", "Design presentations", "Brand assets"],
      permissions: ["write:files", "read:brand_assets"],
      tasksCompleted: 341,
      avgResponseTime: 6.8,
    },
    {
      name: "Legal Agent",
      description: "Reviews contracts, identifies risks, ensures compliance, and drafts standard legal documents.",
      category: "Legal",
      reliabilityScore: 89,
      costScore: 60,
      status: "active",
      supportedModels: ["GPT-4o", "Claude 3.5 Sonnet"],
      strengths: ["Contract review", "Risk identification", "Compliance checking", "Document drafting"],
      useCases: ["Review contracts", "Check compliance", "Draft NDAs", "Identify risks"],
      permissions: ["read:documents", "write:documents"],
      tasksCompleted: 187,
      avgResponseTime: 5.5,
    },
    {
      name: "Finance Agent",
      description: "Analyses financial data, creates reports, monitors transactions, and provides budget insights.",
      category: "Finance",
      reliabilityScore: 97,
      costScore: 82,
      status: "active",
      supportedModels: ["GPT-4o", "Claude 3.5 Sonnet"],
      strengths: ["Financial analysis", "Budget tracking", "Invoice processing", "Xero integration"],
      useCases: ["Analyse financials", "Track expenses", "Generate reports", "Monitor cashflow"],
      permissions: ["read:financial", "read:xero", "write:reports"],
      tasksCompleted: 934,
      avgResponseTime: 1.2,
    },
    {
      name: "Project Agent",
      description: "Tracks project health, identifies risks, manages timelines, and coordinates across teams.",
      category: "Project Management",
      reliabilityScore: 95,
      costScore: 88,
      status: "active",
      supportedModels: ["GPT-4o", "Claude 3.5 Sonnet"],
      strengths: ["Risk assessment", "Timeline management", "Status reporting", "Team coordination"],
      useCases: ["Health check", "Risk review", "Status updates", "Resource planning"],
      permissions: ["read:projects", "write:projects", "read:tasks"],
      tasksCompleted: 1123,
      avgResponseTime: 1.8,
    },
    {
      name: "Security Agent",
      description: "Monitors threats, conducts security scans, manages access controls, and ensures compliance.",
      category: "Security",
      reliabilityScore: 99,
      costScore: 85,
      status: "active",
      supportedModels: ["GPT-4o", "Specialised Security Models"],
      strengths: ["Threat detection", "Access control", "Compliance monitoring", "Vulnerability scanning"],
      useCases: ["Security scan", "Threat analysis", "Compliance check", "Access review"],
      permissions: ["read:security_logs", "read:access_logs", "write:alerts"],
      tasksCompleted: 412,
      avgResponseTime: 0.3,
    },
    {
      name: "Automation Agent",
      description: "Builds and manages workflow automations, integrations, and scheduled tasks.",
      category: "Automation",
      reliabilityScore: 93,
      costScore: 90,
      status: "active",
      supportedModels: ["GPT-4o", "Claude 3.5 Sonnet"],
      strengths: ["Workflow design", "Integration setup", "Trigger management", "Error handling"],
      useCases: ["Build automations", "Schedule tasks", "Connect apps", "Monitor workflows"],
      permissions: ["read:all", "write:workflows", "execute:automations"],
      tasksCompleted: 756,
      avgResponseTime: 2.1,
    },
    {
      name: "Compliance Agent",
      description: "Monitors regulatory changes, checks compliance status, and generates audit reports.",
      category: "Legal",
      reliabilityScore: 92,
      costScore: 75,
      status: "standby",
      supportedModels: ["GPT-4o", "Claude 3.5 Sonnet"],
      strengths: ["Regulatory monitoring", "Audit trails", "Policy compliance", "Risk reporting"],
      useCases: ["Compliance check", "Audit report", "Policy review", "Regulatory update"],
      permissions: ["read:audit_logs", "read:policies", "write:reports"],
      tasksCompleted: 234,
      avgResponseTime: 4.5,
    },
  ]);

  // Projects
  const [project1] = await db.insert(projectsTable).values([
    {
      name: "AITradingMarket",
      description: "An AI-powered trading market platform enabling automated algorithmic trading strategies with real-time market intelligence and risk management.",
      owner: "Alex Morgan",
      status: "active",
      priority: "high",
      progress: 72,
      risks: ["Model accuracy degradation", "Regulatory compliance", "Latency issues"],
      tags: ["AI", "FinTech", "Trading", "Machine Learning"],
      dueDate: "2026-08-15",
    },
  ]).returning();

  const [project2] = await db.insert(projectsTable).values([
    {
      name: "Chameleon",
      description: "Dynamic content personalisation platform that adapts digital experiences in real-time based on user behaviour, preferences, and context.",
      owner: "Sarah Chen",
      status: "active",
      priority: "high",
      progress: 45,
      risks: ["Team bandwidth", "Technical debt in legacy modules", "Q3 deadline pressure"],
      tags: ["AI", "Personalisation", "SaaS", "React"],
      dueDate: "2026-09-30",
    },
  ]).returning();

  const [project3] = await db.insert(projectsTable).values([
    {
      name: "Property Governance Platform",
      description: "Enterprise property management and governance system with compliance tracking, automated reporting, and multi-stakeholder portals.",
      owner: "James Thornton",
      status: "active",
      priority: "critical",
      progress: 88,
      risks: ["Pending regulatory review", "Unresolved stakeholder decisions"],
      tags: ["PropTech", "Governance", "Enterprise", "Compliance"],
      dueDate: "2026-07-01",
    },
  ]).returning();

  const [project4] = await db.insert(projectsTable).values([
    {
      name: "Economic Simulator",
      description: "Macro-economic simulation platform for modelling policy outcomes, market dynamics, and geopolitical scenarios using agent-based modelling.",
      owner: "Dr. Priya Nair",
      status: "active",
      priority: "medium",
      progress: 31,
      risks: ["Model validation complexity", "Data sourcing challenges", "Extended research phase"],
      tags: ["Economics", "Simulation", "Research", "Python"],
      dueDate: "2026-12-31",
    },
  ]).returning();

  const [project5] = await db.insert(projectsTable).values([
    {
      name: "Khameleon Command",
      description: "AI-powered personal command centre — the central operating system for professional and personal digital life.",
      owner: "Alex Morgan",
      status: "active",
      priority: "critical",
      progress: 65,
      risks: ["Integration complexity", "Agent reliability at scale"],
      tags: ["AI", "Platform", "Command Centre", "React", "TypeScript"],
      dueDate: "2026-08-30",
    },
  ]).returning();

  // Tasks
  await db.insert(tasksTable).values([
    { title: "Complete risk model backtesting", status: "in_progress", priority: "urgent", category: "deep_work", recurrence: "one_off", projectId: project1.id, assignee: "Alex Morgan", dueDate: "2026-06-20", aiRecommendation: "Run 5-year historical simulation before next sprint" },
    { title: "Implement real-time order book", status: "todo", priority: "high", category: "deep_work", recurrence: "one_off", projectId: project1.id, assignee: "Dev Team", dueDate: "2026-06-28", aiRecommendation: "Consider WebSocket architecture for latency optimisation" },
    { title: "Regulatory compliance review", status: "todo", priority: "urgent", category: "meetings", recurrence: "one_off", projectId: project1.id, assignee: "Legal Agent", dueDate: "2026-06-25", aiRecommendation: "Schedule Legal Agent for ASIC compliance scan" },
    { title: "Fix personalisation engine accuracy", status: "in_progress", priority: "high", category: "deep_work", recurrence: "one_off", projectId: project2.id, assignee: "Sarah Chen", dueDate: "2026-06-18", aiRecommendation: "A/B test the new recommendation algorithm first" },
    { title: "Stakeholder presentation prep", status: "todo", priority: "high", category: "deep_work", recurrence: "one_off", projectId: project2.id, assignee: "Alex Morgan", dueDate: "2026-06-22", aiRecommendation: "Use Research Agent to gather competitive landscape data" },
    { title: "Final compliance documentation", status: "in_progress", priority: "urgent", category: "deep_work", recurrence: "one_off", projectId: project3.id, assignee: "James Thornton", dueDate: "2026-06-15", aiRecommendation: "Compliance Agent can auto-generate audit trail report" },
    { title: "Stakeholder portal UAT", status: "done", priority: "high", category: "meetings", recurrence: "one_off", projectId: project3.id, assignee: "QA Team", dueDate: "2026-06-10", aiRecommendation: "All critical paths passing, minor UX issues flagged" },
    { title: "Agent-based model calibration", status: "todo", priority: "high", category: "deep_work", recurrence: "one_off", projectId: project4.id, assignee: "Dr. Priya Nair", dueDate: "2026-07-15", aiRecommendation: "Request Research Agent for academic paper synthesis" },
    { title: "Design system implementation", status: "in_progress", priority: "high", category: "deep_work", recurrence: "one_off", projectId: project5.id, assignee: "Design Agent", dueDate: "2026-06-20", aiRecommendation: "DESIGN subagent completing UI build" },
    { title: "API integration testing", status: "todo", priority: "high", category: "task_project_management", recurrence: "one_off", projectId: project5.id, assignee: "Dev Team", dueDate: "2026-06-25", aiRecommendation: "Run end-to-end tests after frontend build completes" },
    { title: "Review investor deck", status: "todo", priority: "medium", category: "deep_work", recurrence: "one_off", projectId: null, assignee: "Alex Morgan", dueDate: "2026-06-19", aiRecommendation: "Suggest using Research Agent for competitive benchmarks" },
    { title: "Prepare board meeting agenda", status: "todo", priority: "high", category: "planning", recurrence: "one_off", projectId: null, assignee: "Alex Morgan", dueDate: "2026-06-17", aiRecommendation: "Calendar Agent can auto-generate pre-read pack" },
  ]);

  // ══════════════════════════════════════════════════════════════════════
  // EXAMPLE DATA — Live Wall parked-reason categories (2026-09-25).
  // One example per reason (external_input / deferred / dependency) so the
  // left column's grouping is visible instead of empty on a fresh seed.
  // DELETE THIS WHOLE BLOCK before shipping the initial prototype — the
  // parked-reason feature itself (schema columns, API fields, the grouped
  // UI in CommandWall.tsx) is real and stays; only these three rows are
  // demo content. Nothing above or below this block depends on it.
  // ══════════════════════════════════════════════════════════════════════
  const [externalInputExample, , dependencyExample] = await db.insert(tasksTable).values([
    { title: "Confirm lease renewal terms with tenant", description: "EXAMPLE DATA - remove before shipping the initial prototype.", status: "blocked", priority: "medium", category: "communication", parkedReason: "external_input", waitingOn: "tenant reply", waitingSince: "2026-09-21T09:00:00Z" },
    { title: "Redesign onboarding email sequence", description: "EXAMPLE DATA - remove before shipping the initial prototype.", status: "todo", priority: "low", category: "deep_work", parkedReason: "deferred", waitingOn: "you paused this to focus on Q3 planning first" },
    { title: "Publish Q3 investor update", description: "EXAMPLE DATA - remove before shipping the initial prototype.", status: "blocked", priority: "high", category: "planning", parkedReason: "dependency" },
  ]).returning();
  await db.update(tasksTable).set({ blockedByTaskId: externalInputExample.id }).where(eq(tasksTable.id, dependencyExample.id));
  // ══════════════════════════════════════════════════════════════════ end

  // Calendar Events
  await db.insert(calendarEventsTable).values([
    {
      title: "AITradingMarket — Sprint Review",
      description: "Review Q2 sprint progress, demo risk model, plan next sprint priorities.",
      startTime: "2026-06-11T09:00:00Z",
      endTime: "2026-06-11T10:30:00Z",
      type: "meeting",
      attendees: ["Alex Morgan", "Sarah Chen", "Dev Team", "James Thornton"],
      location: "Zoom — https://zoom.us/j/123456",
      aiPrep: "Review last sprint velocity (87%), prepare risk model demo, flag regulatory compliance blocker.",
      relatedProject: "AITradingMarket",
      actionItems: ["Update risk model results", "Confirm compliance timeline", "Set next sprint goals"],
    },
    {
      title: "Property Governance — Regulatory Briefing",
      description: "Briefing with legal team on upcoming regulatory changes affecting the platform.",
      startTime: "2026-06-11T13:00:00Z",
      endTime: "2026-06-11T14:00:00Z",
      type: "meeting",
      attendees: ["James Thornton", "Legal Counsel", "Compliance Agent"],
      location: "Boardroom Level 42",
      aiPrep: "Three outstanding compliance items need resolution. Legal Agent has drafted responses for agenda items 2 and 4.",
      relatedProject: "Property Governance Platform",
      actionItems: ["Confirm compliance timeline", "Sign off on audit documentation"],
    },
    {
      title: "Deep Focus: Khameleon Command Architecture",
      description: "Dedicated 2-hour block for architecture review and critical design decisions.",
      startTime: "2026-06-12T07:00:00Z",
      endTime: "2026-06-12T09:00:00Z",
      type: "focus",
      attendees: ["Alex Morgan"],
      location: "Personal",
      aiPrep: "Review agent routing algorithm, security model, and knowledge graph schema.",
      relatedProject: "Khameleon Command",
      actionItems: ["Finalise agent routing logic", "Define knowledge graph entities"],
    },
    {
      title: "Board Meeting — Q2 Review",
      description: "Quarterly board meeting: financial performance, project updates, strategic initiatives.",
      startTime: "2026-06-13T10:00:00Z",
      endTime: "2026-06-13T12:30:00Z",
      type: "meeting",
      attendees: ["Alex Morgan", "Board Members", "CFO", "CTO"],
      location: "HQ Boardroom",
      aiPrep: "Q2 revenue up 34%. AITradingMarket and Chameleon are key discussion items. Property Governance ahead of schedule.",
      relatedProject: "",
      actionItems: ["Present Q2 financials", "Demo Khameleon Command prototype", "Approve Q3 budget"],
    },
    {
      title: "Investor Call — Series B Update",
      description: "Monthly update call with Series B lead investors.",
      startTime: "2026-06-16T15:00:00Z",
      endTime: "2026-06-16T16:00:00Z",
      type: "call",
      attendees: ["Alex Morgan", "Lead Investor", "Co-investor"],
      location: "Teams Call",
      aiPrep: "Prepare KPI dashboard. Highlight AITradingMarket traction and Khameleon Command product vision.",
      relatedProject: "AITradingMarket",
      actionItems: ["Prepare deck", "Update KPI metrics", "Send pre-read"],
    },
    {
      title: "Chameleon — Technical Architecture Review",
      description: "Review the new personalisation engine architecture with senior engineers.",
      startTime: "2026-06-17T11:00:00Z",
      endTime: "2026-06-17T12:30:00Z",
      type: "meeting",
      attendees: ["Sarah Chen", "Lead Engineer", "Alex Morgan"],
      location: "Engineering Room",
      aiPrep: "Chameleon is 45% complete with risk of Q3 delay. Focus on reducing technical debt in the recommendation module.",
      relatedProject: "Chameleon",
      actionItems: ["Review architecture diagram", "Agree on refactor scope", "Update timeline"],
    },
  ]);

  // Inbox Items
  await db.insert(inboxItemsTable).values([
    {
      source: "Email",
      sourceIcon: "Mail",
      sender: "Sarah Chen",
      subject: "Chameleon — Urgent: Personalisation Engine Bug in Production",
      summary: "Critical bug causing 12% accuracy drop in recommendation algorithm. Affects 3 enterprise clients. Hotfix deployed but root cause analysis needed.",
      priority: "critical",
      classification: "decision",
      aiRecommendation: "Assign Coding Agent immediately. Estimated resolution: 4 hours. Notify affected clients proactively.",
      relatedProject: "Chameleon",
      priorityScore: 98,
      isRead: false,
    },
    {
      source: "Teams",
      sourceIcon: "MessageSquare",
      sender: "James Thornton",
      subject: "Property Platform — Regulatory Approval Received",
      summary: "ASIC has approved the property governance framework. Three outstanding compliance items have been resolved. Platform cleared for full launch.",
      priority: "high",
      classification: "task",
      aiRecommendation: "Update project status to 95% complete. Schedule launch announcement for next week.",
      relatedProject: "Property Governance Platform",
      priorityScore: 85,
      isRead: false,
    },
    {
      source: "Slack",
      sourceIcon: "Hash",
      sender: "Dev Team",
      subject: "Khameleon Command — API performance test results",
      summary: "Load testing complete. API handling 2,400 req/s with p99 latency under 120ms. All endpoints passing health checks.",
      priority: "medium",
      classification: "reminder",
      aiRecommendation: "Results exceed targets. Share with stakeholders in next status update.",
      relatedProject: "Khameleon Command",
      priorityScore: 60,
      isRead: false,
    },
    {
      source: "Email",
      sourceIcon: "Mail",
      sender: "Lead Investor",
      subject: "Series B — Follow-up Questions Before Call",
      summary: "Investors requesting detailed breakdown of AITradingMarket ARR projections and a demo of the AI agent orchestration for the board call.",
      priority: "high",
      classification: "decision",
      aiRecommendation: "Assign Research Agent to prepare projections. Schedule 30-min prep call tomorrow.",
      relatedProject: "AITradingMarket",
      priorityScore: 92,
      isRead: false,
    },
    {
      source: "AI Alert",
      sourceIcon: "Bot",
      sender: "Security Agent",
      subject: "Security Alert: Unusual login pattern detected",
      summary: "Two login attempts from unrecognised IP (Singapore) at 03:42 UTC. Both blocked by MFA. No breach detected but investigation recommended.",
      priority: "high",
      classification: "urgent",
      aiRecommendation: "Review access logs. Consider geo-blocking if pattern continues. Security Agent has quarantined the sessions.",
      relatedProject: "",
      priorityScore: 95,
      isRead: false,
    },
    {
      source: "Email",
      sourceIcon: "Mail",
      sender: "Dr. Priya Nair",
      subject: "Economic Simulator — Research Phase Extension Request",
      summary: "Requesting 3-week extension for model validation due to complexity of multi-agent calibration. Provides detailed technical justification.",
      priority: "medium",
      classification: "decision",
      aiRecommendation: "Project Agent estimates this adds minimal risk to overall roadmap. Approval recommended.",
      relatedProject: "Economic Simulator",
      priorityScore: 70,
      isRead: true,
    },
    {
      source: "Calendar",
      sourceIcon: "Calendar",
      sender: "Calendar Agent",
      subject: "Meeting Prep: Board Meeting in 3 Days",
      summary: "Board meeting on June 13 is approaching. Q2 financials ready but investor deck needs updating. 5 action items pending.",
      priority: "high",
      classification: "reminder",
      aiRecommendation: "Begin preparation now. Assign Research Agent for competitive landscape slides.",
      relatedProject: "",
      priorityScore: 88,
      isRead: false,
    },
  ]);

  // Communications
  await db.insert(communicationsTable).values([
    {
      sender: "Sarah Chen",
      senderEmail: "sarah@company.com",
      subject: "Urgent: Chameleon Production Issue",
      source: "email",
      summary: "Critical recommendation engine bug affecting enterprise clients. Hotfix has been deployed but the root cause analysis requires senior developer involvement.",
      sentiment: "urgent",
      priority: "critical",
      suggestedResponse: "Thank you for the immediate action. Please coordinate with the engineering lead and send an RCA report by EOD. I'll notify affected clients.",
      relatedProject: "Chameleon",
      requiredActions: ["Assign engineering lead", "Notify clients", "Request RCA"],
      isRead: false,
    },
    {
      sender: "Lead Investor",
      senderEmail: "investor@venturecap.com",
      subject: "Series B — Due Diligence Follow-up",
      source: "email",
      summary: "Requesting detailed financial models, customer acquisition costs, and a live demo of the AI orchestration capabilities before the next board meeting.",
      sentiment: "positive",
      priority: "high",
      suggestedResponse: "Happy to arrange a demo session. I'll have the financial models prepared by Friday and schedule a walkthrough for Monday.",
      relatedProject: "AITradingMarket",
      requiredActions: ["Prepare financial model", "Schedule demo", "Send confirmation"],
      isRead: false,
    },
    {
      sender: "James Thornton",
      senderEmail: "james@company.com",
      subject: "Property Platform — Launch Clearance",
      source: "teams",
      summary: "Regulatory approval received. Platform ready for production launch. Requesting sign-off on go-live checklist.",
      sentiment: "positive",
      priority: "high",
      suggestedResponse: "Excellent news. Please coordinate final UAT sign-off with the QA team and schedule the launch for next Tuesday.",
      relatedProject: "Property Governance Platform",
      requiredActions: ["Sign go-live checklist", "Schedule launch"],
      isRead: false,
    },
    {
      sender: "Client — Pinnacle Capital",
      senderEmail: "ops@pinnaclecapital.com",
      subject: "Trading Algorithm Performance Review",
      source: "email",
      summary: "Monthly performance review showing 23% outperformance vs benchmark. Client requesting enhanced reporting dashboard and additional risk metrics.",
      sentiment: "positive",
      priority: "medium",
      suggestedResponse: "Delighted with the performance results. I'll arrange for the enhanced dashboard to be included in the next release.",
      relatedProject: "AITradingMarket",
      requiredActions: ["Update dashboard requirements", "Schedule feature review"],
      isRead: true,
    },
    {
      sender: "Dr. Priya Nair",
      senderEmail: "priya@university.edu",
      subject: "Economic Simulator — Academic Collaboration Opportunity",
      source: "email",
      summary: "Two prestigious universities want to co-publish research using the simulator. Requesting permission and potential partnership discussion.",
      sentiment: "positive",
      priority: "medium",
      suggestedResponse: "This is an excellent opportunity. Please send over the collaboration proposal and I'll review it with the legal team.",
      relatedProject: "Economic Simulator",
      requiredActions: ["Review proposal", "Consult legal team"],
      isRead: true,
    },
    {
      sender: "Security Operations",
      senderEmail: "security@company.com",
      subject: "Monthly Security Report — May 2026",
      source: "email",
      summary: "Overall security score 96/100. Two low-severity events logged. All enterprise security benchmarks exceeded. Zero data breaches.",
      sentiment: "neutral",
      priority: "low",
      suggestedResponse: "",
      relatedProject: "",
      requiredActions: [],
      isRead: true,
    },
  ]);

  // Automations
  await db.insert(automationsTable).values([
    {
      name: "Prepare Me For Tomorrow",
      description: "Comprehensive evening briefing covering tomorrow's meetings, pending decisions, and AI recommendations.",
      trigger: "Daily at 18:00",
      status: "active",
      applicationsUsed: ["Calendar", "Email", "Slack", "Projects"],
      requiredPermissions: ["read:calendar", "read:email", "read:projects"],
      requiresApproval: false,
      lastExecution: "2026-06-10T18:00:00Z",
      timeSaved: 45,
      runsCount: 127,
    },
    {
      name: "Inbox Intelligence Summary",
      description: "Processes all overnight messages, classifies by priority, and creates an executive summary.",
      trigger: "Daily at 07:30",
      status: "active",
      applicationsUsed: ["Email", "Teams", "Slack"],
      requiredPermissions: ["read:email", "read:messages"],
      requiresApproval: false,
      lastExecution: "2026-06-11T07:30:00Z",
      timeSaved: 30,
      runsCount: 203,
    },
    {
      name: "Weekly Project Health Report",
      description: "Generates automated project health reports with AI risk analysis and recommendations.",
      trigger: "Every Monday at 08:00",
      status: "active",
      applicationsUsed: ["Projects", "GitHub", "Slack"],
      requiredPermissions: ["read:projects", "read:github"],
      requiresApproval: false,
      lastExecution: "2026-06-09T08:00:00Z",
      timeSaved: 90,
      runsCount: 34,
    },
    {
      name: "Meeting Preparation Brief",
      description: "Automatically prepares comprehensive briefing documents 2 hours before each meeting.",
      trigger: "2 hours before each meeting",
      status: "active",
      applicationsUsed: ["Calendar", "Email", "Research", "Projects"],
      requiredPermissions: ["read:calendar", "read:email", "read:web"],
      requiresApproval: false,
      lastExecution: "2026-06-11T07:00:00Z",
      timeSaved: 25,
      runsCount: 89,
    },
    {
      name: "Security Scan",
      description: "Automated security sweep across all connected systems and access logs.",
      trigger: "Daily at 02:00",
      status: "active",
      applicationsUsed: ["Security", "Vault", "Access Logs"],
      requiredPermissions: ["read:security_logs", "read:access_logs"],
      requiresApproval: false,
      lastExecution: "2026-06-11T02:00:00Z",
      timeSaved: 120,
      runsCount: 342,
    },
    {
      name: "Regulatory Monitoring",
      description: "Monitors regulatory feeds and flags any changes relevant to active projects.",
      trigger: "Twice daily",
      status: "active",
      applicationsUsed: ["Research", "Compliance", "Projects"],
      requiredPermissions: ["read:web", "read:projects"],
      requiresApproval: false,
      lastExecution: "2026-06-11T06:00:00Z",
      timeSaved: 60,
      runsCount: 156,
    },
    {
      name: "Task Follow-up Agent",
      description: "Identifies overdue tasks and generates personalised follow-up messages.",
      trigger: "Weekdays at 16:00",
      status: "active",
      applicationsUsed: ["Tasks", "Email", "Slack", "Teams"],
      requiredPermissions: ["read:tasks", "send:email", "send:messages"],
      requiresApproval: true,
      lastExecution: "2026-06-10T16:00:00Z",
      timeSaved: 20,
      runsCount: 67,
    },
    {
      name: "Client Report Generator",
      description: "Automatically generates monthly client performance reports from project data.",
      trigger: "1st of each month",
      status: "paused",
      applicationsUsed: ["Projects", "Finance", "Email"],
      requiredPermissions: ["read:projects", "read:financial", "send:email"],
      requiresApproval: true,
      lastExecution: "2026-06-01T09:00:00Z",
      timeSaved: 180,
      runsCount: 12,
    },
  ]);

  // Security Layers
  await db.insert(securityLayersTable).values([
    { name: "Layer 1 — Personal Data Protection", description: "Encryption at rest and in transit, PII detection and masking, GDPR compliance monitoring.", status: "secure", score: 98, lastScan: "2026-06-11T02:00:00Z" },
    { name: "Layer 2 — Corporate Confidential Data", description: "DLP controls, access permissions, document classification, external sharing restrictions.", status: "secure", score: 95, lastScan: "2026-06-11T02:00:00Z" },
    { name: "Layer 3 — Password & Credential Vault", description: "Encrypted credential storage, rotation policies, breach monitoring, MFA enforcement.", status: "secure", score: 99, lastScan: "2026-06-11T02:00:00Z" },
    { name: "Layer 4 — AI Access Controls", description: "Agent permission model, AI action audit trail, hallucination detection, output validation.", status: "warning", score: 87, lastScan: "2026-06-11T02:00:00Z" },
    { name: "Layer 5 — Audit & Compliance", description: "Full audit trail, SOC2 controls, regulatory compliance monitoring, access review.", status: "secure", score: 96, lastScan: "2026-06-11T02:00:00Z" },
  ]);

  // Security Events
  await db.insert(securityEventsTable).values([
    { type: "Login Anomaly", severity: "medium", description: "Unusual login attempt from Singapore (IP: 103.x.x.x) at 03:42 UTC. Blocked by MFA.", timestamp: "2026-06-11T03:42:00Z", resolved: false },
    { type: "AI Permission Request", severity: "low", description: "Research Agent requested expanded web access permissions beyond its current scope.", timestamp: "2026-06-10T14:22:00Z", resolved: true },
    { type: "Policy Compliance", severity: "low", description: "Automated compliance scan completed. All systems compliant with current security policies.", timestamp: "2026-06-10T02:00:00Z", resolved: true },
    { type: "Vault Access", severity: "info", description: "Scheduled key rotation completed for 4 API credentials. All rotations successful.", timestamp: "2026-06-09T03:00:00Z", resolved: true },
    { type: "Data Export", severity: "medium", description: "Large data export (2.3GB) initiated by automated report generator. Approved and logged.", timestamp: "2026-06-08T09:15:00Z", resolved: true },
  ]);

  // Vault is a real encrypted secret store now (see routes/vault.ts) — it
  // starts empty for a real user rather than seeding illustrative-but-fake
  // rows, the same call already made for Skill Sets/Integrations.

  // Research Items
  await db.insert(researchItemsTable).values([
    {
      title: "AI Trading Algorithms — Regulatory Landscape 2026",
      description: "Comprehensive analysis of emerging regulations for AI-powered trading systems across APAC, EU, and US markets.",
      type: "Regulatory Research",
      status: "active",
      tags: ["AI", "Trading", "Regulation", "APAC", "ASIC"],
      sources: 23,
      credibilityScore: 94,
      aiSummary: "ASIC released draft guidance in April 2026 requiring AI trading systems to maintain explainability logs. EU AI Act compliance requires risk classification by Q4 2026.",
    },
    {
      title: "Competitor Analysis — Personal AI Assistants",
      description: "Deep dive into competing personal AI platforms: Notion AI, Microsoft Copilot, Google Gemini Advanced, and emerging startups.",
      type: "Competitive Intelligence",
      status: "active",
      tags: ["Competitive", "AI", "Market", "Strategy"],
      sources: 41,
      credibilityScore: 88,
      aiSummary: "Khameleon Command differentiated through multi-agent orchestration and security architecture. Key gap in market: enterprise-grade personal AI with true data isolation.",
    },
    {
      title: "Agent-Based Economic Modelling Literature Review",
      description: "Survey of academic papers on ABM methodology for macro-economic simulation, focusing on recent advances in calibration techniques.",
      type: "Academic Research",
      status: "active",
      tags: ["Economics", "ABM", "Academic", "Methodology"],
      sources: 67,
      credibilityScore: 97,
      aiSummary: "2024-2026 literature shows FLAME GPU 2.0 offering 40x simulation speedup. Santa Fe Institute's latest framework directly applicable to Economic Simulator requirements.",
    },
    {
      title: "Property Governance — ESG Compliance Frameworks",
      description: "Analysis of ESG reporting requirements for commercial property portfolios under upcoming Australian legislation.",
      type: "Compliance Research",
      status: "completed",
      tags: ["ESG", "Property", "Compliance", "Australia"],
      sources: 18,
      credibilityScore: 92,
      aiSummary: "NABERS Energy rating requirements expand to all commercial properties over 1000m² by July 2026. Platform compliance framework already exceeds current requirements.",
    },
    {
      title: "Multi-Agent AI Architecture Patterns",
      description: "Technical survey of architectures for coordinating multiple AI agents with shared context and conflict resolution.",
      type: "Technical Research",
      status: "active",
      tags: ["Architecture", "Multi-Agent", "AI", "Technical"],
      sources: 34,
      credibilityScore: 91,
      aiSummary: "AutoGen and CrewAI patterns provide solid foundation but lack enterprise security isolation. Khameleon Command's approach of isolated agent contexts with shared semantic memory appears novel.",
    },
  ]);

  // Memory Items
  await db.insert(memoryItemsTable).values([
    { category: "Preferences", key: "Writing Style", value: "Direct, concise, no corporate jargon. Use plain English. Bullet points for complex information.", isProtected: true },
    { category: "Preferences", key: "Meeting Preferences", value: "Prefer mornings for deep work. No meetings before 9am or after 5pm unless critical. Maximum 45 minutes per meeting.", isProtected: true },
    { category: "Preferences", key: "Communication Style", value: "Always acknowledge urgency before responding. Lead with conclusions, then reasoning.", isProtected: false },
    { category: "Business Goals", key: "2026 Primary Goal", value: "Launch Khameleon Command to 1,000 enterprise users and achieve $5M ARR by Q4 2026.", isProtected: true },
    { category: "Business Goals", key: "Investment Objective", value: "Close Series B at $20M by August 2026. Focus on AITradingMarket traction for lead narrative.", isProtected: true },
    { category: "Contacts", key: "Lead Investor", value: "Preferred contact channel: WhatsApp for urgent items, email for formal communication. Responds within 2 hours.", isProtected: false },
    { category: "Contacts", key: "Key Clients", value: "Pinnacle Capital (trading), PropertyGroup APAC (governance), ANU Economic Research. Quarterly check-ins required.", isProtected: false },
    { category: "Workflows", key: "Morning Routine", value: "Review overnight inbox summary at 7:30. Check project dashboards at 8:00. First meeting no earlier than 9:00.", isProtected: false },
    { category: "Workflows", key: "Decision Framework", value: "For decisions >$50K: require 48h consideration period. For strategic decisions: consult board before committing.", isProtected: true },
    { category: "Workflows", key: "AI Agent Trust Level", value: "Automate: scheduling, inbox triage, reports. Require approval: emails to clients, data exports, financial actions.", isProtected: true },
  ]);

  // Approvals
  await db.insert(approvalsTable).values([
    { action: "Send Email", requestingAgent: "Email Agent", reason: "Auto-reply to Lead Investor requesting Series B demo scheduling", riskLevel: "medium", dataInvolved: "External communication, investor details", status: "pending" },
    { action: "Share File", requestingAgent: "Research Agent", reason: "Share competitive analysis report with external consultant for review", riskLevel: "medium", dataInvolved: "Confidential strategy document", status: "pending" },
    { action: "Connect Application", requestingAgent: "Automation Agent", reason: "Connect Xero accounting to Finance Agent for automated reconciliation", riskLevel: "high", dataInvolved: "Financial data access", status: "pending" },
    { action: "Run Automation", requestingAgent: "Automation Agent", reason: "Execute monthly client report generation for Pinnacle Capital", riskLevel: "low", dataInvolved: "Project metrics and performance data", status: "pending" },
    { action: "Access Vault", requestingAgent: "Coding Agent", reason: "Request GitHub PAT to initiate automated code review on PR #247", riskLevel: "medium", dataInvolved: "Repository access credentials", status: "pending" },
    { action: "Export Data", requestingAgent: "Finance Agent", reason: "Export Q2 financial data for board meeting presentation", riskLevel: "high", dataInvolved: "Financial records, revenue data", status: "pending" },
    { action: "Send Email", requestingAgent: "Calendar Agent", reason: "Send meeting confirmation and agenda to all board meeting attendees", riskLevel: "low", dataInvolved: "Meeting details and agenda", status: "approved", resolvedAt: "2026-06-10T14:00:00Z" },
    { action: "Run Automation", requestingAgent: "Security Agent", reason: "Run scheduled security scan on all connected integrations", riskLevel: "low", dataInvolved: "Access logs and security metadata", status: "approved", resolvedAt: "2026-06-11T01:00:00Z" },
  ]);

  // Insights
  await db.insert(insightsTable).values([
    { message: "Project Chameleon is at risk of a 3-week delay based on current sprint velocity and backlog size.", category: "Project Risk", confidenceScore: 0.89, priority: "high", actionRequired: true, relatedProject: "Chameleon" },
    { message: "You have 6 pending approvals that have been waiting over 4 hours. Recommend immediate review.", category: "Action Required", confidenceScore: 0.99, priority: "critical", actionRequired: true, relatedProject: "" },
    { message: "Board meeting preparation is 40% complete. 3 days remaining. Recommend starting the investor deck today.", category: "Deadline Alert", confidenceScore: 0.95, priority: "high", actionRequired: true, relatedProject: "" },
    { message: "Property Governance Platform has unresolved stakeholder decisions blocking final sign-off.", category: "Project Risk", confidenceScore: 0.87, priority: "high", actionRequired: true, relatedProject: "Property Governance Platform" },
    { message: "Security Agent detected a medium-severity login anomaly 6 hours ago. No action has been taken.", category: "Security", confidenceScore: 0.98, priority: "critical", actionRequired: true, relatedProject: "" },
    { message: "Research Agent identified a regulatory change affecting AITradingMarket. Review recommended within 48 hours.", category: "Compliance", confidenceScore: 0.91, priority: "high", actionRequired: true, relatedProject: "AITradingMarket" },
    { message: "Economic Simulator research phase extension is low-risk given current project portfolio. Approval recommended.", category: "Recommendation", confidenceScore: 0.82, priority: "medium", actionRequired: false, relatedProject: "Economic Simulator" },
    { message: "AI agent cost optimisation opportunity: consolidating Email and Communication agents could reduce costs by 18%.", category: "Optimisation", confidenceScore: 0.78, priority: "low", actionRequired: false, relatedProject: "" },
  ]);

  // Marketplace Agents
  await db.insert(marketplaceAgentsTable).values([
    { name: "GPT-4o", description: "OpenAI's most capable multimodal model. Excels at complex reasoning, coding, and analysis.", provider: "OpenAI", category: "Foundation Model", accuracyScore: 96, costScore: 72, speedScore: 88, reliabilityScore: 97, privacyScore: 78, isInstalled: true, version: "2024-11-20", pricing: "$0.0025/1K tokens" },
    { name: "Claude 3.5 Sonnet", description: "Anthropic's flagship model with exceptional reasoning and safety characteristics.", provider: "Anthropic", category: "Foundation Model", accuracyScore: 95, costScore: 74, speedScore: 85, reliabilityScore: 96, privacyScore: 85, isInstalled: true, version: "20241022", pricing: "$0.003/1K tokens" },
    { name: "Gemini Ultra", description: "Google's most powerful multimodal AI with deep Google Workspace integration.", provider: "Google", category: "Foundation Model", accuracyScore: 93, costScore: 70, speedScore: 90, reliabilityScore: 94, privacyScore: 82, isInstalled: false, version: "1.5-pro", pricing: "$0.0035/1K tokens" },
    { name: "Llama 3.3 70B", description: "Meta's open-source model offering strong performance with full data privacy.", provider: "Meta (Open Source)", category: "Open Source", accuracyScore: 88, costScore: 98, speedScore: 78, reliabilityScore: 90, privacyScore: 99, isInstalled: false, version: "3.3-70b", pricing: "Self-hosted / Free" },
    { name: "Mistral Large", description: "Enterprise-grade European AI with strong multilingual and coding capabilities.", provider: "Mistral AI", category: "Foundation Model", accuracyScore: 91, costScore: 85, speedScore: 88, reliabilityScore: 92, privacyScore: 90, isInstalled: false, version: "2411", pricing: "$0.002/1K tokens" },
    { name: "Perplexity API", description: "Real-time web-connected AI for up-to-date research and factual queries.", provider: "Perplexity", category: "Research Specialised", accuracyScore: 90, costScore: 80, speedScore: 82, reliabilityScore: 93, privacyScore: 76, isInstalled: true, version: "sonar-pro", pricing: "$0.001/query" },
    { name: "DeepSeek Coder V3", description: "State-of-the-art code generation and analysis model optimised for engineering tasks.", provider: "DeepSeek", category: "Code Specialised", accuracyScore: 94, costScore: 92, speedScore: 86, reliabilityScore: 91, privacyScore: 80, isInstalled: false, version: "v3-0324", pricing: "$0.00028/1K tokens" },
    { name: "o3 Reasoning", description: "OpenAI's advanced reasoning model for complex problem-solving and analysis.", provider: "OpenAI", category: "Reasoning Specialised", accuracyScore: 98, costScore: 45, speedScore: 55, reliabilityScore: 95, privacyScore: 78, isInstalled: false, version: "o3-2025-04-16", pricing: "$0.01/1K tokens" },
  ]);

  console.log("Seeding complete!");
}

seed().catch(console.error);
